development:
  host: localhost
  database: landing_page_development

test:
  host: localhost
  database: landing_page_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
